# .air.toml

# Build settings
[build]
# Command to compile the Go application
cmd = "go build -o ./tmp/main ./cmd/cli/main.go" # Adjust the build command as needed
bin = "start_with_tmux.sh"
# Optional delay after file changes before rebuilding (in milliseconds)
delay = 1000
# Directory to exclude from file monitoring (optional)
exclude_dir = ["tmp", "vendor"]
# File extensions to include in monitoring
include_ext = ["go", "tmpl", "html"]
