[tools]
"cargo:bacon"          = "latest"
"cargo:cargo-dist"     = "^0.25.1"
"cargo:cargo-edit"     = "latest"
"cargo:cargo-feature"  = "latest"
"cargo:cargo-generate" = "latest"
"cargo:cargo-machete"  = "latest"
"cargo:cargo-nextest"  = "latest"
"cargo:git-cliff"      = "latest"
"cargo:just"           = "latest"
"uv"                   = "latest"

[tasks.default]
description = "Run bacon"
run         = ["bacon"]
