[tools]
"cargo:git-cliff" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-feature" = "latest"
"cargo:cargo-dist" = "^0.25.1"
"cargo:bacon" = "latest"
"cargo:cargo-machete" = "latest"
"cargo:cargo-generate" = "latest"
"cargo:just" = "latest"
"uv" = "latest"

[tasks.default]
description = "Run bacon"
run = ["bacon"]
